import { Post, Story, Profile } from '@/types';

// ─── Current Authenticated User ──────────────────────────────────────────────
export const MOCK_CURRENT_USER: Profile = {
  id: 'user-me-001',
  username: 'me',
  full_name: 'You',
  bio: 'Living the Stubgram life 🔥 | Content creator & explorer.',
  avatar_url: 'https://i.pravatar.cc/150?img=32',
  cover_url: 'https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?w=1200&q=80',
  is_verified: false,
  is_celebrity: false,
  account_type: 'regular',
  followers_count: 128,
  following_count: 94,
  posts_count: 12,
  coins: 450,
  premium_plan: 'free',
  created_at: '2024-06-15T10:00:00Z',
};

// ─── Mock Users (with real portrait photos from pravatar.cc) ─────────────────
export const MOCK_USERS: Profile[] = [
  {
    id: 'user-001',
    username: 'selena_creates',
    full_name: 'Selena Martinez',
    bio: 'Lifestyle creator | Travel junkie 🌍 | Brand deals: dm@selena.com',
    avatar_url: 'https://i.pravatar.cc/150?img=47',
    cover_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
    is_verified: true,
    is_celebrity: true,
    account_type: 'vip',
    followers_count: 2_450_000,
    following_count: 312,
    posts_count: 847,
    premium_plan: 'premium_plus',
    created_at: '2022-01-10T09:00:00Z',
  },
  {
    id: 'user-002',
    username: 'codewithkev',
    full_name: 'Kevin Osei',
    bio: 'Full-stack dev | Building cool stuff with Next.js & AI ⚡',
    avatar_url: 'https://i.pravatar.cc/150?img=12',
    cover_url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&q=80',
    is_verified: true,
    is_celebrity: false,
    account_type: 'industry',
    followers_count: 84_200,
    following_count: 506,
    posts_count: 234,
    premium_plan: 'premium',
    created_at: '2022-08-22T14:00:00Z',
  },
  {
    id: 'user-003',
    username: 'amara.glow',
    full_name: 'Amara Diallo',
    bio: 'Beauty & wellness 💄 | Natural hair advocate | IG: @amaraglow',
    avatar_url: 'https://i.pravatar.cc/150?img=45',
    cover_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&q=80',
    is_verified: false,
    is_celebrity: false,
    account_type: 'regular',
    followers_count: 9_870,
    following_count: 1_204,
    posts_count: 412,
    premium_plan: 'basic',
    created_at: '2023-03-05T11:00:00Z',
  },
  {
    id: 'user-004',
    username: 'jakethephoto',
    full_name: 'Jake Thornton',
    bio: 'Documentary photographer 📷 | Moments that matter',
    avatar_url: 'https://i.pravatar.cc/150?img=8',
    cover_url: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1200&q=80',
    is_verified: true,
    is_celebrity: false,
    account_type: 'industry',
    followers_count: 320_400,
    following_count: 89,
    posts_count: 1_021,
    premium_plan: 'premium',
    created_at: '2021-11-18T08:00:00Z',
  },
  {
    id: 'user-005',
    username: 'nadia.eats',
    full_name: 'Nadia Wright',
    bio: 'Food blogger | Michelin star dreams 🍽️ | Recipe drops every Friday',
    avatar_url: 'https://i.pravatar.cc/150?img=23',
    cover_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=80',
    is_verified: false,
    is_celebrity: false,
    account_type: 'regular',
    followers_count: 54_100,
    following_count: 2_341,
    posts_count: 678,
    premium_plan: 'basic',
    created_at: '2023-06-20T16:00:00Z',
  },
  {
    id: 'user-006',
    username: 'marcus.fit',
    full_name: 'Marcus Reid',
    bio: 'Fitness coach | @nike athlete | Transform your body in 90 days 💪',
    avatar_url: 'https://i.pravatar.cc/150?img=11',
    cover_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=1200&q=80',
    is_verified: true,
    is_celebrity: false,
    account_type: 'industry',
    followers_count: 1_240_000,
    following_count: 204,
    posts_count: 532,
    premium_plan: 'premium_plus',
    created_at: '2021-05-14T13:00:00Z',
  },
];

// ─── Mock Posts ───────────────────────────────────────────────────────────────
const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600 * 1000).toISOString();

export const MOCK_POSTS: Post[] = [
  {
    id: 'post-001',
    user_id: 'user-001',
    users: {
      id: 'user-001',
      username: 'selena_creates',
      full_name: 'Selena Martinez',
      avatar: 'https://i.pravatar.cc/150?img=47',
      isVerified: true,
      isCelebrity: true,
      followersCount: 2_450_000,
      followingCount: 312,
      postsCount: 847,
      createdAt: '',
      email: '',
    },
    type: 'image',
    content: 'Golden hour hits different when you\'re on a rooftop in Santorini 🌅 No filter needed when the world is this beautiful.',
    media_url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
    likes_count: 84_231,
    comments_count: 3_412,
    shares_count: 892,
    is_liked: false,
    created_at: hoursAgo(1),
    updated_at: hoursAgo(1),
  },
  {
    id: 'post-002',
    user_id: 'user-002',
    users: {
      id: 'user-002',
      username: 'codewithkev',
      full_name: 'Kevin Osei',
      avatar: 'https://i.pravatar.cc/150?img=12',
      isVerified: true,
      isCelebrity: false,
      followersCount: 84_200,
      followingCount: 506,
      postsCount: 234,
      createdAt: '',
      email: '',
    },
    type: 'text',
    content: 'Hot take: You don\'t need 10 years of experience to build something that matters.\n\nI built my first SaaS 6 months into coding. It made $0. But I learned more in those 6 months than 2 years of courses.\n\nStop waiting to be "ready". Ship the ugly MVP. Iterate. Learn.',
    likes_count: 12_487,
    comments_count: 891,
    shares_count: 4_231,
    is_liked: true,
    created_at: hoursAgo(3),
    updated_at: hoursAgo(3),
  },
  {
    id: 'post-003',
    user_id: 'user-003',
    users: {
      id: 'user-003',
      username: 'amara.glow',
      full_name: 'Amara Diallo',
      avatar: 'https://i.pravatar.cc/150?img=45',
      isVerified: false,
      isCelebrity: false,
      followersCount: 9_870,
      followingCount: 1_204,
      postsCount: 412,
      createdAt: '',
      email: '',
    },
    type: 'image',
    content: 'My Sunday skincare routine has been a game changer 🌿 Tag someone who needs to try this!',
    media_url: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&q=80',
    likes_count: 2_104,
    comments_count: 318,
    shares_count: 47,
    is_liked: false,
    created_at: hoursAgo(5),
    updated_at: hoursAgo(5),
  },
  {
    id: 'post-004',
    user_id: 'user-004',
    users: {
      id: 'user-004',
      username: 'jakethephoto',
      full_name: 'Jake Thornton',
      avatar: 'https://i.pravatar.cc/150?img=8',
      isVerified: true,
      isCelebrity: false,
      followersCount: 320_400,
      followingCount: 89,
      postsCount: 1_021,
      createdAt: '',
      email: '',
    },
    type: 'image',
    content: 'The faces of resilience. A series documenting small business owners rebuilding after the floods. 📷 #Documentary #Community',
    media_url: 'https://images.unsplash.com/photo-1531545514256-b1400bc00f31?w=800&q=80',
    likes_count: 45_789,
    comments_count: 2_103,
    shares_count: 8_941,
    is_liked: false,
    created_at: hoursAgo(8),
    updated_at: hoursAgo(8),
  },
  {
    id: 'post-005',
    user_id: 'user-005',
    users: {
      id: 'user-005',
      username: 'nadia.eats',
      full_name: 'Nadia Wright',
      avatar: 'https://i.pravatar.cc/150?img=23',
      isVerified: false,
      isCelebrity: false,
      followersCount: 54_100,
      followingCount: 2_341,
      postsCount: 678,
      createdAt: '',
      email: '',
    },
    type: 'image',
    content: 'Truffle pasta from scratch — this recipe took me 3 tries to perfect. Save this, you will NEED it. 🍝✨\n\n#FoodBlogger #Recipes #PastaLovers',
    media_url: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80',
    likes_count: 8_902,
    comments_count: 674,
    shares_count: 1_204,
    is_liked: false,
    created_at: hoursAgo(12),
    updated_at: hoursAgo(12),
  },
  {
    id: 'post-006',
    user_id: 'user-001',
    users: {
      id: 'user-001',
      username: 'selena_creates',
      full_name: 'Selena Martinez',
      avatar: 'https://i.pravatar.cc/150?img=47',
      isVerified: true,
      isCelebrity: true,
      followersCount: 2_450_000,
      followingCount: 312,
      postsCount: 847,
      createdAt: '',
      email: '',
    },
    type: 'text',
    content: 'PSA: You are allowed to rest. You are allowed to not be productive every day. You are allowed to just exist without constantly optimizing yourself. 💙\n\nTake the break. The world will still be here.',
    likes_count: 234_101,
    comments_count: 15_892,
    shares_count: 89_043,
    is_liked: true,
    created_at: hoursAgo(16),
    updated_at: hoursAgo(16),
  },
  {
    id: 'post-007',
    user_id: 'user-006',
    users: {
      id: 'user-006',
      username: 'marcus.fit',
      full_name: 'Marcus Reid',
      avatar: 'https://i.pravatar.cc/150?img=11',
      isVerified: true,
      isCelebrity: false,
      followersCount: 1_240_000,
      followingCount: 204,
      postsCount: 532,
      createdAt: '',
      email: '',
    },
    type: 'image',
    content: '6am workout hits different 🔥 No excuses. The gym is your best therapist, your best mentor, and your best investment. Day 47 of 90. Who\'s with me? 💪 #FitnessJourney #NoDaysOff',
    media_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80',
    likes_count: 54_312,
    comments_count: 3_201,
    shares_count: 7_840,
    is_liked: false,
    created_at: hoursAgo(20),
    updated_at: hoursAgo(20),
  },
  {
    id: 'post-008',
    user_id: 'user-002',
    users: {
      id: 'user-002',
      username: 'codewithkev',
      full_name: 'Kevin Osei',
      avatar: 'https://i.pravatar.cc/150?img=12',
      isVerified: true,
      isCelebrity: false,
      followersCount: 84_200,
      followingCount: 506,
      postsCount: 234,
      createdAt: '',
      email: '',
    },
    type: 'image',
    content: 'Just deployed Stubgram\'s new feed algorithm. 10x faster cold starts using edge functions. 🚀',
    media_url: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80',
    likes_count: 6_302,
    comments_count: 492,
    shares_count: 2_109,
    is_liked: false,
    created_at: hoursAgo(24),
    updated_at: hoursAgo(24),
  },
  {
    id: 'post-009',
    user_id: 'user-004',
    users: {
      id: 'user-004',
      username: 'jakethephoto',
      full_name: 'Jake Thornton',
      avatar: 'https://i.pravatar.cc/150?img=8',
      isVerified: true,
      isCelebrity: false,
      followersCount: 320_400,
      followingCount: 89,
      postsCount: 1_021,
      createdAt: '',
      email: '',
    },
    type: 'image',
    content: 'Mountains at dawn — Cathedral Peak, Drakensberg. No tourists, just me and 100 kg of camera gear. 😅 Worth every step.',
    media_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    likes_count: 91_034,
    comments_count: 4_201,
    shares_count: 12_800,
    is_liked: false,
    created_at: hoursAgo(36),
    updated_at: hoursAgo(36),
  },
  {
    id: 'post-010',
    user_id: 'user-003',
    users: {
      id: 'user-003',
      username: 'amara.glow',
      full_name: 'Amara Diallo',
      avatar: 'https://i.pravatar.cc/150?img=45',
      isVerified: false,
      isCelebrity: false,
      followersCount: 9_870,
      followingCount: 1_204,
      postsCount: 412,
      createdAt: '',
      email: '',
    },
    type: 'image',
    content: 'Cleaned out my wardrobe and donated 60% of it. Capsule wardrobe incoming ✨ Less is genuinely more.',
    media_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    likes_count: 3_891,
    comments_count: 247,
    shares_count: 309,
    is_liked: false,
    created_at: hoursAgo(48),
    updated_at: hoursAgo(48),
  },
];

// ─── Mock Stories (with real face avatars) ────────────────────────────────────
const storyCreated = (h: number) => new Date(now.getTime() - h * 3600 * 1000).toISOString();
const storyExpires = (h: number) => new Date(now.getTime() + (24 - h) * 3600 * 1000).toISOString();

export const MOCK_STORIES: Story[] = [
  {
    id: 'story-001',
    user_id: 'user-001',
    user: { id: 'user-001', username: 'selena_creates', full_name: 'Selena Martinez', avatar_url: 'https://i.pravatar.cc/150?img=47', is_verified: true },
    media_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80',
    type: 'image',
    caption: 'Morning coffee in Positano ☕',
    created_at: storyCreated(2),
    expires_at: storyExpires(2),
    viewed: false,
  },
  {
    id: 'story-002',
    user_id: 'user-002',
    user: { id: 'user-002', username: 'codewithkev', full_name: 'Kevin Osei', avatar_url: 'https://i.pravatar.cc/150?img=12', is_verified: true },
    media_url: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&q=80',
    type: 'image',
    caption: 'Late night coding sessions hit different 💻',
    created_at: storyCreated(4),
    expires_at: storyExpires(4),
    viewed: false,
  },
  {
    id: 'story-003',
    user_id: 'user-003',
    user: { id: 'user-003', username: 'amara.glow', full_name: 'Amara Diallo', avatar_url: 'https://i.pravatar.cc/150?img=45', is_verified: false },
    media_url: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&q=80',
    type: 'image',
    caption: 'Self care Sunday 🌿',
    created_at: storyCreated(6),
    expires_at: storyExpires(6),
    viewed: true,
  },
  {
    id: 'story-004',
    user_id: 'user-004',
    user: { id: 'user-004', username: 'jakethephoto', full_name: 'Jake Thornton', avatar_url: 'https://i.pravatar.cc/150?img=8', is_verified: true },
    media_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
    type: 'image',
    caption: 'Somewhere in the Alps 🏔️',
    created_at: storyCreated(8),
    expires_at: storyExpires(8),
    viewed: false,
  },
  {
    id: 'story-005',
    user_id: 'user-005',
    user: { id: 'user-005', username: 'nadia.eats', full_name: 'Nadia Wright', avatar_url: 'https://i.pravatar.cc/150?img=23', is_verified: false },
    media_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80',
    type: 'image',
    caption: 'The best burger in the city 🍔',
    created_at: storyCreated(10),
    expires_at: storyExpires(10),
    viewed: true,
  },
  {
    id: 'story-006',
    user_id: 'user-006',
    user: { id: 'user-006', username: 'marcus.fit', full_name: 'Marcus Reid', avatar_url: 'https://i.pravatar.cc/150?img=11', is_verified: true },
    media_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80',
    type: 'image',
    caption: 'Morning gains 💪',
    created_at: storyCreated(12),
    expires_at: storyExpires(12),
    viewed: false,
  },
];

// ─── Paginated Feed Helper ────────────────────────────────────────────────────
export function getMockFeed(cursor?: string | null, limit = 5) {
  const startIndex = cursor ? MOCK_POSTS.findIndex((p) => p.id === cursor) + 1 : 0;
  const slice = MOCK_POSTS.slice(startIndex, startIndex + limit);
  const hasMore = startIndex + limit < MOCK_POSTS.length;
  const nextCursor = hasMore ? slice[slice.length - 1]?.id : null;
  return { data: slice, hasMore, nextCursor };
}

// ─── Profile Helpers ──────────────────────────────────────────────────────────
export function getMockProfile(username: string): Profile | null {
  const special = username === 'me' ? MOCK_CURRENT_USER : null;
  return special ?? MOCK_USERS.find((u) => u.username === username) ?? null;
}

export function getMockUserPosts(userId: string): Post[] {
  return MOCK_POSTS.filter((p) => p.user_id === userId);
}
